services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ruccos-six-pack
      MYSQL_DATABASE: school_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Make sure schema.sql is in the same directory as this file
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:

